services:
  - type: web
    name: ncert-ai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"  # Added build command
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"  # Changed to production server
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: PORT  # Required by Render
        value: 10000
      - key: FLASK_DEBUG  # Explicit debug control
        value: "false"
